# Generated by Django 2.1.2 on 2018-10-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=32)),
                ('notice_data', models.TextField()),
                ('notice_picture', models.CharField(max_length=32)),
                ('notice_time', models.CharField(max_length=20)),
            ],
        ),
    ]
