# Generated by Django 2.1.2 on 2018-10-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='电影名称')),
                ('movie_cate', models.CharField(blank=True, max_length=30, null=True, verbose_name='电影分类')),
                ('movie_img', models.CharField(blank=True, max_length=300, null=True, verbose_name='封面图片')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('viewed', models.BooleanField(default=False, verbose_name='观看状态')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'ordering': ('name',),
            },
        ),
    ]
